# https://phptoday.ru/post/gotovim-lokalnuyu-sredu-docker-dlya-razrabotki-na-php
# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
  nginx:
    container_name: tp_nginx
    # используем последний стабильный образ nginx
    image: nginx:latest
    restart: always
    networks:
      - application_network
    # маршрутизируем порты
    ports:
      - "80:80"
      - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./docker/hosts:/etc/nginx/conf.d
      - .:/var/www
      - ./docker/logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    container_name: tp_php
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./docker/images/php
    restart: always
    networks:
      - application_network
    # этот образ будет общаться с mysql
    links:
      - db
    depends_on:
      - db
    # монтируем директорию с проектами
    volumes:
      - .:/var/www:cached
  db:
    container_name: tp_db
    image: mariadb:10.3
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    networks:
      - application_network
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tp
      MYSQL_USER: tp
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - tp_db:/var/lib/mysql
volumes:
  tp_db:
    external: true
networks:
  application_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.18.0/24

